server:
  port: 8000

eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: global filter
            isPreLogger: true
            isPostLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET, POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
            - Method=GET, POST
          filters:
            - RewritePath=/catalog-service/(?<segment>.*), /$\{segment}

        ## 테스트 실습
#        - id: my-first-service
#          uri: lb://MY-FIRST-SERVICE
#          predicates:
#            - Path=/first-service/**
#          filters:
#            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=first-request, first-request-header
#            - AddResponseHeader=first-response, first-response-header
#            - CustomFilter
#        - id: my-second-service
#          uri: lb://MY-SECOND-SERVICE
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: logging filter
#                isPreLogger: true
#                isPostLogger: true
