server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 
